// Generated by CoffeeScript 1.9.3
(function() {
  var colors, fonts, pageWidth;

  colors = ["#fc4267", "#ff6600", "#cc916a", "#ffde58", "#77c261", "#f14700", "#ffffff"];

  fonts = [16, 22, 26];

  $('#marquee').marquee();

  pageWidth = $("#video-wrap").width();

  $('button').click(function() {
    var d;
    d = $('#marquee .wrap:eq(0) span').filter(function() {
      var elementLeft, elementWidth;
      elementWidth = $(this).width();
      elementLeft = $(this).position().left;
      if (pageWidth - (elementWidth + elementLeft) < 0) {
        return false;
      } else {
        return true;
      }
    });
    console.log(d);
    return $('#marquee').marquee('pause');
  });

}).call(this);
